version: '3.9'

services:

  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  app:
    build:
      context: .
    command: >
      sh -c "python manage.py wait_for_db &&
              python manage.py makemigrations &&
              python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8000"
    restart: always
    volumes:
      - ./pinmage:/pinmage
      - ./data/p_web:/vol/p_web
    ports:
      - 8000:8000
    environment:
      - DJANGO_SETTINGS_MODULE=pinmage.settings.local
      - SECRET_KEY=U0F74JrTEnp2qoFTII4lFj1H0TK0LfXeTSTWufoP2vY
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - db

  