# Generated by Django 4.1.5 on 2023-02-15 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="photo",
            field=models.ImageField(
                default="default_profile.png",
                max_length=500,
                upload_to="users/%Y/%m/%d",
            ),
        ),
    ]
